### PR TITLE
fix webpack4 deprecation warnings

### PR DESCRIPTION
**Pull request by zhaoyiyi**

### CODE REVIEW

**Comment by pmowrer** [comment]
Thanks for handling this @zhaoyiyi! Just to verify, is it backwards compatible with webpack 3?

**Comment by zhaoyiyi** [comment]
Thanks for asking @pmowrer, I didn't think about backward compatibility at all when making the changes.

It is not compatible with webpack 3. So do you want to bump the version to 2.0 or do a `if (compiler.hooks) ... else` check.

**Comment by pmowrer** [comment]
I think we should do the conditional since its just a deprecation warning. Please also make a comment to remove the old plugin handling in the next major version. Thanks!

**Comment by zhaoyiyi** [comment]
Thanks @pmowrer, PR updated

**Comment by pmowrer** [comment]
Fantastic, thanks again!

**Pull request merged**
